# Generated by Django 4.2.10 on 2024-03-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_stand', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ad', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('video_ad', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('time', models.TimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
                ('ad_shown_duration', models.IntegerField(default=0)),
                ('stand', models.ManyToManyField(related_name='ads', to='app.stand')),
            ],
        ),
    ]
